build.zig, src/metrics/instrument.zig, src/metrics/meter.zig, src/metrics/reader.zig, src/metrics/spec.zig, src/pbutils.zig
Adding unit test to ensure `MetricReader.collect()` actually exports data.
The additional test `metric reader collects data from meter provider` is marked as leaking by the testing allocator.
Here's the output
```
☁  opentelemetry-zig [reader-test] zig build test              
test
└─ run test 33/33 passed, 1 leaked
error: 'metrics.reader.test.metric reader collects data from meter provider' leaked: Instrument with identifying name some-counter-Counter--72014e4eed7eeb7d already exists in meter my-meter
[gpa] (err): memory address 0x7f943f672040 leaked: 
/usr/local/zig-linux-x86_64-0.13.0/lib/std/fmt.zig:1802:36: 0x109f80e in allocPrint__anon_10778 (test)
const buf = try allocator.alloc(u8, size);
^
/home/francesco/Projects/inge4pres/opentelemetry-zig/src/metrics/spec.zig:193:34: 0x109bbee …
```
=> Add test for reader, correct references and their allocation and cleanup

src/api/trace.zig, src/api/trace/config.zig, src/api/trace/provider.zig, src/api/trace/tracer.zig, src/sdk.zig, src/sdk/trace.zig, src/sdk/trace/provider.zig
this PR references [sdk package](https://github.com/open-telemetry/opentelemetry-go/tree/main/sdk) and [trace package](https://github.com/open-telemetry/opentelemetry-go/tree/main/trace) in opentelemetry-go.
- `TracerProvider` in trace API (ref https://opentelemetry.io/docs/specs/otel/trace/api/#tracerprovider)
- `TracerProvider` implementation (ref https://opentelemetry.io/docs/specs/otel/trace/sdk/#tracer-provider)
- currently the provider does nothing (for keeping the PR small)
- `Tracer` in trace API ( ref https://opentelemetry.io/docs/specs/otel/trace/api/#tracer)
Let's discuss about the project structure and dependency relations are reasonable for all.
=> Add the simple TracerProvider API and the SDK implementation

build.zig, src/api.zig, src/api/metrics.zig, src/api/metrics/measurement.zig
Since we split the API and SDK through #9, we forgot to add test calls to the moved files in the newly created `api` module.
Add a new test artifact to the build script to allow tests execution for the `api` module.
Notice that by checking out only the first commit, the wrong import in api/metrics/measurment.zig#L2 is throwing an error previously uncaught, because the tests were never compiled.
```
git checkout c0e08c7a890c91a7f83ff9edd6e962695d9e0dd7
zig build test -- "measurement"
```
You can see the error (fixed in the second commit).
This means that the API tests were not executed prior.
=> build: add api module in test step

build.zig.zon, src/opentelemetry/proto/common/v1.pb.zig, src/opentelemetry/proto/metrics/v1.pb.zig
Upgrading to latest release of the protobuf code generator
Release notes https://github.com/Arwalk/zig-protobuf/releases/tag/v2.0.0
=> deps: update protobuf-zig to v2.0.0

.github/workflows/test.yaml, build.zig, examples/metrics/basic.zig, examples/metrics/http_server.zig, src/sdk.zig
Closes #8 
We add a new `zig build examples` command to the project's build: it will build an run all `.zig` files in the `examples/<signal>` folders.
While we haven't yet filled in examples for trace and logs, we have a basic build structure that can be extended once the signals are implemented.
`build.zig` will also have to be updated adding trace/logs examples build when we have examples to be made.
- create a new build step
- export the `metrics` types that are needed to be consumed when importing the SDK library module
- minor cosmetic improvements in `build.zig`
=> Build: add `examples` step

build.zig, build.zig.zon, examples/metrics/basic.zig, examples/metrics/http_server.zig, src/api/metrics/instrument.zig, src/api/metrics/measurement.zig, src/api/metrics/meter.zig, src/attributes.zig, src/sdk.zig, src/sdk/metrics/exporter.zig, src/sdk/metrics/exporters/otlp.zig, src/sdk/metrics/reader.zig, src/sdk/metrics/view.zig
Part of #11 
This is a rather big PR, where the commit history might help reviewing 🙏🏼 
It is a big change because so far, all the interactions across multiple components were happening through protobuf-generated types.
With this PR, we introduce smaller and easier to use types, that are also easier to move around.
There's also a semantic change in metrics collection that is more in-line with the OTel philosophy: metrics' data points are never aggregated by the instruments, but only at collection time.
This is a small memory footprint increase traded for more accuracy and modularity in the metrics exporting.
=> Metrics: isolate `protobuf` dependency 

src/api/metrics/instrument.zig, src/api/metrics/measurement.zig, src/api/metrics/meter.zig, src/attributes.zig, src/sdk/metrics/exporter.zig
Fixes #19 
The metrics currently do not have any thread-safety between measurements recording and collection/exporting.
This PR adds a mutex to guard the instruments implementations across data races that are possible because the data points are recorded by different threads than the one exporting them to Metric Reader(s).
=> Metrics: make record and collection thread-safe

examples/metrics/basic.zig, examples/metrics/http_server.zig, src/api/metrics/instrument.zig, src/api/metrics/measurement.zig, src/api/metrics/meter.zig, src/attributes.zig, src/sdk.zig, src/sdk/metrics/exporter.zig, src/sdk/metrics/exporters/in_memory.zig, src/sdk/metrics/exporters/otlp.zig, src/sdk/metrics/exporters/stdout.zig, src/sdk/metrics/reader.zig, src/sdk/metrics/view.zig
Part 1 of #15 
InMemory exporter was already partially implemented, and implementing Stdout was relatively straightforward.
I took the chance to apply some refactoring, inspired after re-reading the OTel specification in the section that explains how exporters would interact with `MetricExporter` and `MetricReader`.
Reviewing commit by commit might be easier.
While working on the next 2 exporters missing to close #15, I stumbled on a design problem regarding Histogram that I will address in the upcoming PR.
This is why there is a seemingly spurious commit on changing the measurements; it'll be part of the next refactoring I'm working on to support exporting histogram data points correctly.
=> Metrics: stable exporters part 1

benchmarks/metrics/instrument.zig, build.zig, src/api/metrics/instrument.zig, src/api/metrics/measurement.zig, src/api/metrics/meter.zig, src/sdk.zig
I mentioned I had discovered a problem in histogram while developing exporters in #37.
The problem that this PR fixes is that the histogram data points must be storing each field on a per-attribute basis.
Currently, the fields are always set, disregarding the attributes.
* (unrelated to this PR) Fix build process running twice for SDK tests (it was due to testing API)
* Fix the histogram collection in `record`
* Improve the `AggregatedMetrics.aggregate` function
* Add benchmarks for histogram
=> Metrics: Histogram stores datapoints by attributes

src/api/metrics/instrument.zig, src/api/metrics/meter.zig, src/api/metrics/spec.zig, src/sdk/metrics/reader.zig
Closes #38.
We overlooked the specification when uilding the getMeter API,
confusing the meter registration with instrument registration.
Signed-off-by: inge4pres <fgualazzi@gmail.com>
=> metrics: replace `MeterOptions` with `InstrumentationScope`

src/attributes.zig, src/scope.zig
Previously, the hashing mechanism did not account for the order of attributes, leading to inconsistent hash values for the same set of attributes in different orders. This could cause issues when using `InstrumentationScope` as a key in hash maps, as equivalent scopes with different attribute orders would produce different hash values.
- Modified `Attributes.HashContext.hash` to sort attributes by key before hashing
- Added a fast path for small numbers of attributes (≤8) to avoid allocation
Added a new test case `InstrumentationScope hash should be consistent regardless of attribute order` that verifies:
- Hash values are equal for the same attributes in different orders
- The eql method correctly identifies equivalent attribute sets
closes …
=> fix: add sort before hashing attributes

src/api/metrics/instrument.zig, src/api/metrics/measurement.zig, src/api/metrics/meter.zig, src/otlp.zig, src/sdk.zig, src/sdk/metrics/exporter.zig, src/sdk/metrics/exporters/in_memory.zig, src/sdk/metrics/exporters/otlp.zig, src/sdk/metrics/exporters/stdout.zig, src/sdk/metrics/reader.zig
> [!NOTE]
> **This is a big PR**
> Reviewing it commit by commit might be easier
Part of #15: adds OTLP protocol implementation and its exporter counterpart, consuming the protocol.
We are restricting the implementation to the bare minimum that satisfies the specification:
* OTLP configuration via env vars
* OTLP _only_ using HTTP as transport (no gRPC, as it does not seem to be yet full support for it in `protobuf-zig`, but I may be wrong)
* OTLP has retries for HTTP responses, following the specs
* The exporter relies on the same `MetricExporter` design previously delivering the other stable exporters
Some miscellaneous additions and fixes arose from getting the protobuf conversion running, they are included in this PR.
There is not great test coverage for the OTLP exporter, mainly …
=> Metrics: implement OTLP and its exporter

.github/workflows/deploy-docs.yml, build.zig
This PR introduces two key improvements to our documentation workflow:
- Introduced a new build step (`docs`) to generate project documentation.
- Added `.github/workflows/deploy-docs.yml`.
- The workflow is triggered on every push to the `master` branch.
- Steps:
- Checks out the code and sets up Zig.
- Runs the new `zig build docs` step.
- Uploads the generated documentation as a Pages artifact.
- Deploys the artifact to GitHub Pages using the official `actions/deploy-pages` action.
- Verified that `zig build docs` produces the expected output locally.
closes https://github.com/zig-o11y/opentelemetry-sdk/issues/52
=> feat(build): add docs build step to build.zig & deploy docs job

.github/workflows/deploy-docs.yml
used a non-existing version 4 of `upload-pages-artifact`.
tested and verified on my fork:
https://hendriknielaender.github.io/opentelemetry-sdk/
=> fix(ci): upload-pages-artifact use v3

src/otlp.zig
=> otlp: config HTTP client with `OTLP_` env vars

src/api.zig, src/api/context.zig, src/api/context/context.zig, src/sdk.zig
This PR introduces a robust, thread-safe, and spec-compliant implementation of the OpenTelemetry Context API.
https://opentelemetry.io/docs/specs/otel/context/
- **Immutable Contexts:**  
Contexts are immutable by design, ensuring safe concurrent access and compliance with the OpenTelemetry specification. All mutation operations return a new context instance.
- **Thread-Local Context Stack:**  
Implements a thread-local stack for implicit context propagation, following OpenTelemetry's LIFO attach/detach semantics. This enables context to flow transparently through the call stack without explicit parameter passing.
- **Extensive Test Coverage:**  
Includes a suite of tests covering key creation, context immutability, stack operations, error handling, and chaining semantics.
```zig
const …
```
=> feat: add context api

build.zig, examples/metrics/otlp.zig, examples/otlp_stub/server.zig, src/api/metrics.zig, src/api/metrics/spec.zig, src/opentelemetry/proto/proto.zig, src/otlp.zig, src/otlp_test.zig, src/pbutils.zig, src/sdk.zig, src/sdk/metrics/exporter.zig, src/sdk/metrics/exporters/otlp.zig, src/sdk/metrics/reader.zig, src/sdk/metrics/view.zig
Closes #60.
We add an example of how to consume the OTKP exporter.
A bigger change was needed to extract the protobuf-generated code into its own module.
It's an internal module, so it's not visible to library users.
The example shows that the API to work with current OTLP design is a bit clunky.
Will raise a card to adress improriving it in the future.
=> examples: add OTLP example

build.zig, src/api/metrics/instrument.zig, src/api/metrics/meter.zig, src/otlp.zig, src/otlp_test.zig, src/sdk/metrics/exporter.zig, src/sdk/metrics/exporters/otlp.zig, src/sdk/metrics/exporters/stdout.zig, src/sdk/metrics/reader.zig, src/test_runner.zig
This PR improves the test output and logging system by replacing `std.debug.print` calls with proper `std.log` functions and implementing a custom test runner to capture log output during tests, eliminating stderr warnings while preserving valuable debugging information.
- Converted all debug print statements to use the appropriate log levels (err, warn, debug)
- Added scoped logging for better organization and filtering:
- `.otlp` - OTLP transport module
- `.otlp_test` - OTLP test module
- `.instrument` - Metrics instrument module
- `.meter` - Meter module
- `.exporter` - Metrics exporter module
- `.otlp_exporter` - OTLP exporter module
- `.stdout_exporter` - Stdout exporter module
- `.reader` - Metrics reader module
Based on https://www.openmymind.net/Using-A-Custom-Test-Runner-In-Zig/ …
=> feat: add custom test runner & scoped logs

benchmarks/metrics/attribute.zig, benchmarks/metrics/histogram.zig, examples/metrics/histogram.zig, examples/metrics/http_server.zig, src/api/metrics/instrument.zig, src/api/metrics/meter.zig, src/api/metrics/spec.zig, src/sdk.zig, src/sdk/metrics/aggregation.zig, src/sdk/metrics/exporter.zig, src/sdk/metrics/reader.zig, src/sdk/metrics/view.zig
**This is a rather big PR** as it involves a refactoring of the Histogram, initiated in #82.
On top of the refactor, this PR also adds the `view.View` component, that is needed to fulfill the specification.
Closes #66 
* finish the aggregation framework changes to allow Base2 Exp histograms to be fully working
* add the `View` component
* wire the View into MeterProvider
* amend accordingly benchmarks and examples
=> Metrics: add View, amend examples and bench

.github/workflows/deploy-docs.yml, .github/workflows/test.yaml
Use the mirror built with https://github.com/inge4pres/zigmirror.com
=> ci: use external mirror in setup-zig

examples/trace/multiple_tracers.zig, examples/trace/simple.zig, src/sdk.zig, src/sdk/trace.zig, src/sdk/trace/exporter.zig, src/sdk/trace/exporters/generic.zig, src/sdk/trace/exporters/otlp.zig, src/sdk/trace/id_generator.zig, src/sdk/trace/provider.zig, src/sdk/trace/span_exporter.zig, src/sdk/trace/span_processor.zig
Implement the `trace` SDK with dynamic dispatch in exporters.
This PR adds support for calling into the `sdk.trace` module to create traces and spans.
The dynamic dispatch might be revisited in the future, at least in the exporter.
The hot paths are already removed of indirect calls to VTables, a tagged union is used to statically dispatch the implementation needed.
Benchmarks are missing, those are going to be added in #35.
Examples are amended to consume the new module.
=> Trace: implement SDK

benchmarks/trace/span.zig, examples/trace/simple.zig, src/api/trace/span.zig, src/api/trace/tracer.zig, src/sdk.zig, src/sdk/trace/exporters/generic.zig, src/sdk/trace/exporters/otlp.zig, src/sdk/trace/provider.zig, src/sdk/trace/span_processor.zig
In the current implementation, spans do not carry the scope associated with the Tracer.
This PR adds support for it.
Closes #94.
* Wire the tracers' instrumentation scope into all spans
* Group spans by scope when exporting OTLP
Examples updated accordingly.
=> Trace: add instrumentation scope to spans

benchmarks/trace/span.zig, benchmarks/trace/trace.zig, examples/trace/multiple_tracers.zig, examples/trace/simple.zig, src/api/trace.zig, src/api/trace/trace_flags.zig, src/api/trace/tracer.zig, src/sdk/metrics/exporter.zig, src/sdk/trace.zig, src/sdk/trace/provider.zig
The previous implementation of traces SDK used standalone types.
The API components were also concrete types that were not compliant with the specification.
* Turn the API trace components into interfaces
* Implement correctly the interface, preserving the functionality
* clear up spans resources on end
Related to #9
=> Trace: API separation from SDK
